List<String> technologyList = [
  'smartfon',
  'tablet',
  'laptop',
  'serwer',
  'programowanie',
  'kryptowaluty',
  'blockchain',
  'sztuczna inteligencja',
  'drony',
  'gry wideo',
  'VR (Virtual Reality)',
  'AR (Augmented Reality)',
  'sieci 5G',
  'internet rzeczy (IoT)',
  'bazowanie GPS',
  'cloud computing',
  'cyberbezpieczeństwo',
  'data science',
  'rozwój aplikacji mobilnych',
  'biotechnologia',
  'elektryczne pojazdy',
  'autonomiczne pojazdy',
  'energetyka odnawialna',
  'nanotechnologia',
  'rozpoznawanie mowy',
  'analiza danych',
  'robotyka',
  'automatyka przemysłowa',
  'druk 3D',
  'mikrokontrolery',
  'sieci neuronowe',
  'rozpoznawanie obrazów',
  'sztuczne sieci neuronowe',
  'e-commerce',
  'inżynieria genetyczna',
  'technologie noszalne',
  'przetwarzanie języka naturalnego',
  'chatboty',
  'machine learning',
  'deep learning',
  'Big Data',
  'telemedycyna',
  'e-podpisy',
  'bezprzewodowe ładowanie',
  'optymalizacja SEO',
  'analityka internetowa',
  'social media marketing',
  'blockchain w finansach',
  'digital twin',
  'quantum computing',
  'technologie chmurowe',
  'rozwój oprogramowania',
  'hacking etyczny',
  'internet satelitarny',
  'fotowoltaika',
  'technologia MEMS',
  'geoinformatyka',
  'czujniki IoT',
  'technologia RFID',
  'modelowanie 3D',
  'cyber-physical systems',
  'systemy wbudowane',
  'przetwarzanie w chmurze',
  'bezpieczeństwo aplikacji',
  'elektroniczne systemy płatności',
  'technologie sieciowe',
  'technologie bezdotykowe',
  'technologie LED',
  'mikroprocesory',
  'inteligentne domy',
  'telekomunikacja',
  'satelity',
  'elektromobilność',
  'systemy operacyjne',
  'technologia nano',
  'inżynieria jądrowa',
  'technologia informacyjna',
  'automatyzacja procesów',
  'inżynieria przemysłowa',
  'inteligentne systemy transportowe',
  'technologia baterii',
  'cyberfizyczne systemy produkcji',
  'diagnostyka medyczna',
  'elektryczność statyczna',
  'inżynieria geotechniczna',
  'technologia laserowa',
  'mechanika stosowana',
  'nanotechnologie w medycynie',
  'optyka',
  'technologia satelitarna',
  'sieci komputerowe',
  'bezpieczeństwo sieci',
  'technologie kwantowe',
  'fotonika',
  'elektrotechnika',
  'telewizja cyfrowa',
  'technologie audio',
  'internet wysokich prędkości',
  'roboty przemysłowe',
  'technologie sensoryczne',
  'informatyka kwantowa',
  'rozwiązania VR w edukacji',
  'systemy zarządzania bazami danych'
];

List<String> vehicleMechanicsList = [
  'Wymiana oleju',
  'wymiana filtrów',
  'regulacja zaworów',
  'wymiana paska rozrządu',
  'wymiana opon',
  'wyważanie kół',
  'geometria kół',
  'serwis klimatyzacji',
  'naprawa układu hamulcowego',
  'wymiana klocków hamulcowych',
  'wymiana tarcz hamulcowych',
  'serwis układu zawieszenia',
  'wymiana amortyzatorów',
  'wymiana sprzęgła',
  'naprawa skrzyni biegów',
  'diagnostyka komputerowa',
  'naprawa silnika',
  'czyszczenie wtryskiwaczy',
  'wymiana świec zapłonowych',
  'wymiana cewki zapłonowej',
  'naprawa układu chłodzenia',
  'wymiana płynu chłodniczego',
  'wymiana termostatu',
  'serwisowanie turbosprężarki',
  'naprawa układu wydechowego',
  'spawanie tłumika',
  'wymiana oleju w skrzyni biegów',
  'wymiana filtra powietrza',
  'wymiana filtra paliwa',
  'wymiana filtra kabinowego',
  'wymiana płynu hamulcowego',
  'wymiana płynu wspomagania',
  'wymiana akumulatora',
  'ładowanie akumulatora',
  'naprawa alternatora',
  'naprawa rozrusznika',
  'wymiana paska klinowego',
  'wymiana paska wielorowkowego',
  'wymiana łożyska koła',
  'wymiana piasty',
  'naprawa układu kierowniczego',
  'wymiana końcówek drążka',
  'wymiana przegubów',
  'wymiana osłon przegubów',
  'wymiana wahaczy',
  'wymiana sworzni wahacza',
  'wymiana tulei wahacza',
  'wymiana drążków kierowniczych',
  'wymiana łącznika stabilizatora',
  'wymiana tulei stabilizatora',
  'wymiana poduszki silnika',
  'wymiana poduszki skrzyni biegów',
  'naprawa uszczelki pod głowicą',
  'planowanie głowicy',
  'wymiana paska napędu osprzętu',
  'wymiana rolki napinającej',
  'wymiana rolki prowadzącej',
  'wymiana pompy wody',
  'wymiana czujnika temperatury',
  'wymiana czujnika ciśnienia oleju',
  'wymiana czujnika położenia wału korbowego',
  'wymiana czujnika położenia wałka rozrządu',
  'wymiana czujnika ABS',
  'wymiana czujnika ciśnienia w oponach',
  'wymiana czujnika parkowania',
  'kalibracja czujników',
  'wymiana lamp',
  'wymiana żarówek',
  'regulacja świateł',
  'wymiana reflektorów',
  'naprawa elektryki pojazdu',
  'wymiana bezpieczników',
  'wymiana przekaźników',
  'naprawa systemu audio',
  'aktualizacja oprogramowania pojazdu',
  'wymiana szyb',
  'naprawa szyberdachu',
  'wymiana uszczelek drzwi',
  'smarowanie zawiasów',
  'wymiana zamka',
  'wymiana lusterka',
  'naprawa podgrzewania siedzeń',
  'wymiana tapicerki',
  'czyszczenie wnętrza pojazdu',
  'polerowanie karoserii',
  'naprawa rdzy',
  'naprawa zderzaków',
  'wymiana kierunkowskazów',
  'wymiana wycieraczek',
  'wymiana spryskiwaczy',
  'wymiana pompy spryskiwaczy',
  'wymiana zbiornika płynu do spryskiwaczy',
  'wymiana dyfuzora powietrza',
  'wymiana chłodnicy',
  'wymiana intercoolera',
  'wymiana przewodów paliwowych',
  'wymiana przewodów hamulcowych',
  'wymiana przewodów hydraulicznych',
  'wymiana przewodów pneumatycznych'
];

List<String> vehicleMechanicsItemsList = [
  'Silnik',
  'skrzynia biegów',
  'turboładowarka',
  'alternator',
  'rozrusznik',
  'tłumik',
  'filtr powietrza',
  'filtr oleju',
  'filtr paliwa',
  'filtr kabinowy',
  'świeca zapłonowa',
  'świeca żarowa',
  'wtryskiwacz',
  'pompka paliwa',
  'akumulator',
  'pasek rozrządu',
  'pasek klinowy',
  'rolka napinacza',
  'pompka sprzęgła',
  'płyn hamulcowy',
  'tarcza hamulcowa',
  'klocki hamulcowe',
  'zacisk hamulcowy',
  'rura wydechowa',
  'koło',
  'opona',
  'zawór opony',
  'piasta koła',
  'łożysko koła',
  'wahacz',
  'sprężyna zawieszenia',
  'amortyzator',
  'stabilizator',
  'drążek kierowniczy',
  'przekładnia kierownicza',
  'maglownica',
  'przegub',
  'osłona przegubu',
  'przewód hamulcowy',
  'przewód paliwowy',
  'przewód olejowy',
  'przewód klimatyzacji',
  'chłodnica',
  'intercooler',
  'termostat',
  'czujnik temperatury',
  'czujnik ciśnienia oleju',
  'czujnik położenia wału',
  'czujnik ABS',
  'czujnik ciśnienia w oponach',
  'czujnik parkowania',
  'lampa',
  'żarówka',
  'reflektor',
  'kierunkowskaz',
  'lusterko',
  'szyba',
  'wycieraczka',
  'spryskiwacz',
  'pompa spryskiwacza',
  'zbiornik płynu do spryskiwaczy',
  'zamek drzwi',
  'klamka',
  'zawias drzwi',
  'poduszka powietrzna',
  'pas bezpieczeństwa',
  'fotel',
  'tapicerka',
  'dywanik',
  'kierownica',
  'licznik',
  'radio',
  'głośnik',
  'antena',
  'moduł sterujący',
  'bezpiecznik',
  'przekaźnik',
  'czujnik parkowania',
  'czujnik deszczu',
  'czujnik światła',
  'czujnik temperatury zewnętrznej',
  'dysza wtryskowa',
  'korbowód',
  'wał korbowy',
  'tłok',
  'pierścień tłokowy',
  'głowica',
  'uszczelka pod głowicą',
  'wałek rozrządu',
  'zawór ssący',
  'zawór wydechowy',
  'pompa oleju',
  'pompa wody',
  'obudowa termostatu',
  'obudowa filtra oleju',
  'zbiornik płynu chłodzącego',
  'zbiornik wyrównawczy',
  'zbiornik płynu hamulcowego',
  'zbiornik płynu wspomagania',
  'manometr ciśnienia oleju',
  'klucz dynamometryczny',
  'podnośnik',
  'lewarek',
  'klucz do kół',
  'zestaw narzędzi',
  'tester diagnostyczny',
  'ładowarka do akumulatora',
  'kompresor powietrza'
];

List<String> wardrobeList = [
  'Koszula',
  'spodnie',
  'jeansy',
  'garnitur',
  'marynarka',
  'krawat',
  'muszka',
  'sweter',
  't-shirt',
  'polo',
  'bluza',
  'szorty',
  'bermudy',
  'płaszcz',
  'kurtka',
  'trencz',
  'puchówka',
  'kurtka skórzana',
  'kurtka bomber',
  'kurtka jeansowa',
  'kurtka wiatrówka',
  'kurtka parka',
  'kamizelka',
  'koszulka termoaktywna',
  'bielizna',
  'bokserki',
  'slipy',
  'piżama',
  'szlafrok',
  'kąpielówki',
  'szlafmyca',
  'skarpety',
  'skarpetki sportowe',
  'skarpetki klasyczne',
  'szalik',
  'czapka',
  'kapelusz',
  'rękawiczki',
  'pas',
  'portfel',
  'torba',
  'plecak',
  'buty',
  'buty sportowe',
  'buty eleganckie',
  'mokasyny',
  'trampki',
  'sandały',
  'klapki',
  'zegarek',
  'bransoletka',
  'łańcuszek',
  'pierścionek',
  'okulary przeciwsłoneczne',
  'okulary korekcyjne',
  'mankietówki',
  'spinki do krawata',
  'szelki',
  'pasek do spodni',
  'pasek skórzany',
  'pasek tkaninowy',
  'koszulka z długim rękawem',
  'koszulka na ramiączkach',
  'koszulka polo',
  'koszulka z nadrukiem',
  'bluza z kapturem',
  'bluza bez kaptura',
  'bluza rozpinana',
  'bluza ocieplana',
  'kardigan',
  'sweter z golfem',
  'sweter rozpinany',
  'sweter z okrągłym dekoltem',
  'sweter z V-dekoltem',
  'koszula z długim rękawem',
  'koszula z krótkim rękawem',
  'koszula flanelowa',
  'koszula jeansowa',
  'koszula biznesowa',
  'koszula casualowa',
  'koszula w kratę',
  'koszula w paski',
  'garnitur jednorzędowy',
  'garnitur dwurzędowy',
  'garnitur trzyczęściowy',
  'garnitur slim fit',
  'garnitur na miarę',
  'garnitur w kratę',
  'garnitur w paski',
  'spodnie materiałowe',
  'spodnie chinos',
  'spodnie lniane',
  'spodnie cargo',
  'spodnie dresowe',
  'spodnie jogger',
  'spodnie biznesowe',
  'spodnie casualowe',
  'spodnie w kratę',
  'spodnie w paski',
  'spodnie z mankietem',
  'spodnie z lampasami',
  'pasek do garnituru',
  'kurtka puchowa',
  'kurtka przeciwdeszczowa',
  'kurtka narciarska',
  'kurtka trekkingowa',
  'płaszcz wełniany',
  'płaszcz zimowy',
  'płaszcz przeciwdeszczowy',
  'płaszcz długopis',
  'szal wełniany',
  'szal jedwabny',
  'szal kaszmirowy',
  'krawat jedwabny',
  'krawat wełniany',
  'muszka jedwabna',
  'muszka wełniana'
];

List<String> carRepairShopItemsList = [
  'Klucz płaski',
  'klucz oczkowy',
  'klucz nasadowy',
  'zestaw nasadek',
  'klucz dynamometryczny',
  'wkrętak płaski',
  'wkrętak krzyżakowy',
  'wkrętak torx',
  'zestaw śrubokrętów',
  'szczypce',
  'szczypce zaciskowe',
  'kombinerki',
  'obcęgi',
  'młotek',
  'młotek gumowy',
  'młotek ślusarski',
  'piła do metalu',
  'pilnik',
  'imadło',
  'szczotka druciana',
  'papier ścierny',
  'taśma izolacyjna',
  'taśma dwustronna',
  'miara zwijana',
  'poziomica',
  'tester napięcia',
  'multimetr',
  'lutownica',
  'zestaw do lutowania',
  'klej termotopliwy',
  'pistolet do kleju',
  'pistolet do silikonu',
  'smar',
  'olej silnikowy',
  'płyn hamulcowy',
  'płyn chłodniczy',
  'płyn do spryskiwaczy',
  'antyzamarzacz',
  'pasta polerska',
  'wosk do karoserii',
  'szpachla',
  'zestaw do naprawy opon',
  'kompresor powietrza',
  'manometr',
  'podnośnik hydrauliczny',
  'lewarek',
  'podstawki pod auto',
  'kanał',
  'zestaw kluczy imbusowych',
  'zestaw kluczy torx',
  'zestaw kluczy hakowych',
  'klucz do filtrów oleju',
  'klucz do kół',
  'maszynka do wyważania kół',
  'wyważarka do kół',
  'maszyna do wymiany opon',
  'szczotka do czyszczenia kół',
  'szczotka do czyszczenia wnętrza',
  'odkurzacz warsztatowy',
  'szmaty',
  'rękawice robocze',
  'okulary ochronne',
  'maska przeciwpyłowa',
  'kombinezon roboczy',
  'buty robocze',
  'zestaw pierwszej pomocy',
  'pojemnik na zużyty olej',
  'pojemnik na odpady',
  'puszka na śmieci',
  'lampa warsztatowa',
  'latarka',
  'lampa inspekcyjna',
  'tester akumulatora',
  'ładowarka do akumulatorów',
  'zestaw narzędziowy',
  'kufer narzędziowy',
  'skrzynka narzędziowa',
  'półka na narzędzia',
  'wózek narzędziowy',
  'wózek do przechowywania',
  'stół warsztatowy',
  'stojak na narzędzia',
  'wiertarka',
  'wiertła',
  'szlifierka kątowa',
  'tarcze do szlifierki',
  'narzędzie wielofunkcyjne',
  'zestaw do naprawy gwintów',
  'urządzenie do diagnostyki komputerowej',
  'oprogramowanie diagnostyczne',
  'kamera inspekcyjna',
  'dźwignia montażowa',
  'rozwierak',
  'zaciskarka',
  'urządzenie do spawania',
  'elektrody spawalnicze',
  'maska spawalnicza',
  'butla z gazem',
  'zestaw do naprawy układu klimatyzacji',
  'urządzenie do napełniania klimatyzacji',
  'stacja obsługi klimatyzacji',
  'zestaw do czyszczenia wtryskiwaczy',
  'maszyna do czyszczenia wtryskiwaczy',
  'zestaw do czyszczenia układu paliwowego',
  'zestaw do czyszczenia układu chłodzenia',
  'probówka do płynów eksploatacyjnych',
  'zbiornik na płyny eksploatacyjne',
  'wąż do oleju',
  'pompka do oleju',
  'pompka do paliwa',
  'wąż do paliwa'
];

List<String> generalListMen = [
  'zegarek męski',
  'portfel skórzany',
  'męski pasek do spodni',
  'okulary przeciwsłoneczne',
  'garnitur',
  'krawat',
  'muszka',
  'spinki do mankietów',
  'torba na laptopa',
  'aktówka',
  'kurtka skórzana',
  'koszula',
  'buty eleganckie',
  'buty sportowe',
  'zegarek sportowy',
  'plecak',
  'kurtka puchowa',
  'sweter',
  'bluza',
  't-shirt',
  'bokserki',
  'piżama',
  'szlafrok',
  'szorty',
  'jeansy',
  'spodnie chinos',
  'spodnie dresowe',
  'kurtka bomber',
  'kurtka jeansowa',
  'kurtka wiatrówka',
  'kurtka trekkingowa',
  'płaszcz',
  'trencz',
  'czapka z daszkiem',
  'czapka zimowa',
  'rękawiczki',
  'szalik',
  'koszulka polo',
  'koszulka termoaktywna',
  'bielizna termoaktywna',
  'kąpielówki',
  'szlafmyca',
  'skarpetki',
  'skarpetki sportowe',
  'skarpety klasyczne',
  'okulary korekcyjne',
  'naszyjnik',
  'bransoletka',
  'pierścionek',
  'łańcuszek',
  'zegarek nurkowy',
  'zegarek pilotowy',
  'zegarek taktyczny',
  'mankietówki',
  'szelki',
  'pasek skórzany',
  'pasek tkaninowy',
  'torba sportowa',
  'torba podróżna',
  'walizka',
  'nerka',
  'sakwa rowerowa',
  'ręcznik',
  'klapki',
  'sandały',
  'trampki',
  'mokasyny',
  'buty trekkingowe',
  'buty narciarskie',
  'buty do biegania',
  'buty do piłki nożnej',
  'kask rowerowy',
  'kask motocyklowy',
  'kask narciarski',
  'gogle narciarskie',
  'gogle pływackie',
  'rękawice rowerowe',
  'rękawice bokserskie',
  'rękawice robocze',
  'rękawice narciarskie',
  'ochraniacze na nogi',
  'ochraniacze na ręce',
  'plecak turystyczny',
  'plecak wspinaczkowy',
  'namiot',
  'śpiwór',
  'karimata',
  'latarka',
  'latarka czołowa',
  'kompas',
  'zegarek z GPS',
  'smartwatch',
  'opaska fitness',
  'hantle',
  'kettlebell',
  'mata do ćwiczeń',
  'ręcznik sportowy',
  'bidon',
  'shaker do odżywek',
  'torba na sprzęt sportowy',
  'rakieta tenisowa',
  'piłka nożna',
  'piłka do koszykówki',
  'piłka do rugby',
  'kij golfowy',
  'kij baseballowy',
  'rakieta do badmintona',
  'rakieta do squasha',
  'wędka',
  'kołowrotek',
  'nóż myśliwski',
  'nóż taktyczny',
  'nóż wielofunkcyjny',
  'latarka taktyczna',
  'okulary taktyczne',
  'kamizelka taktyczna'
];

List<String> homeRenovationList = [
  'Malowanie ścian',
  'tapetowanie',
  'szpachlowanie',
  'kładzenie płytek',
  'montaż paneli podłogowych',
  'wymiana okien',
  'montaż drzwi',
  'instalacja elektryczna',
  'hydraulika',
  'montaż kuchni',
  'remont łazienki',
  'tynkowanie',
  'montaż sufitu podwieszanego',
  'izolacja termiczna',
  'montaż ogrzewania podłogowego',
  'położenie parkietu',
  'montaż schodów',
  'szlifowanie drewna',
  'lakierowanie',
  'wyrównywanie podłogi',
  'montaż listew przypodłogowych',
  'montaż parapetów',
  'montaż karniszy',
  'montaż rolet',
  'układanie wykładziny',
  'montaż armatury łazienkowej',
  'montaż mebli',
  'wymiana blatów kuchennych',
  'montaż oświetlenia',
  'malowanie sufitu',
  'tapetowanie sufitu',
  'montaż wentylacji',
  'montaż klimatyzacji',
  'montaż alarmu',
  'montaż systemów inteligentnego domu',
  'prace zbrojarskie',
  'prace murarskie',
  'stawianie ścianek działowych',
  'montaż izolacji akustycznej',
  'uszczelnianie',
  'montaż kabin prysznicowych',
  'układanie kostki brukowej',
  'prace dekarskie',
  'montaż rynien',
  'montaż dachu',
  'montaż okapów',
  'montaż kominka',
  'montaż ogrzewania',
  'montaż fotowoltaiki',
  'montaż instalacji gazowej'
];

List<String> financesList = [
  'Bilans',
  'zysk',
  'strata',
  'aktywa',
  'pasywa',
  'inwestycja',
  'rentowność',
  'akcje',
  'obligacje',
  'dług',
  'kapitał',
  'budżet',
  'amortyzacja',
  'renta',
  'dywidenda',
  'waluta',
  'kurs walutowy',
  'inflacja',
  'deflacja',
  'stopy procentowe',
  'kredyt',
  'pożyczka',
  'leasing',
  'płynność finansowa',
  'fundusz inwestycyjny',
  'portfel inwestycyjny',
  'zarządzanie ryzykiem',
  'rynek finansowy',
  'rynek kapitałowy',
  'rynek walutowy',
  'analiza finansowa',
  'sprawozdanie finansowe',
  'rachunek zysków i strat',
  'bilans płatniczy',
  'wskaźnik finansowy',
  'marża',
  'spread',
  'bankowość',
  'ubezpieczenia',
  'emerytura',
  'fundusz emerytalny',
  'fundusz rezerwowy',
  'podatek',
  'oszczędności',
  'lokata',
  'budżetowanie',
  'audyt',
  'kontrola finansowa',
  'rachunkowość',
  'zarządzanie finansami'
];

List<String> itNetworksList = [
  'Protokół TCP/IP',
  'router',
  'switch',
  'serwer',
  'firewall',
  'VPN (Virtual Private Network)',
  'LAN (Local Area Network)',
  'WAN (Wide Area Network)',
  'WLAN (Wireless Local Area Network)',
  'DNS (Domain Name System)',
  'IPv4',
  'IPv6',
  'adres IP',
  'maska podsieci',
  'gateway',
  'NAT (Network Address Translation)',
  'DHCP (Dynamic Host Configuration Protocol)',
  'FTP (File Transfer Protocol)',
  'HTTP (Hypertext Transfer Protocol)',
  'HTTPS (Hypertext Transfer Protocol Secure)',
  'SSL (Secure Sockets Layer)',
  'TLS (Transport Layer Security)',
  'sieć peer-to-peer',
  'topologia sieci',
  'Ethernet',
  'Wi-Fi',
  'SSID',
  'WEP (Wired Equivalent Privacy)',
  'WPA (Wi-Fi Protected Access)',
  'WPA2',
  'SNMP (Simple Network Management Protocol)',
  'SMTP (Simple Mail Transfer Protocol)',
  'POP3 (Post Office Protocol 3)',
  'IMAP (Internet Message Access Protocol)',
  'VoIP (Voice over Internet Protocol)',
  'QoS (Quality of Service)',
  'BGP (Border Gateway Protocol)',
  'OSPF (Open Shortest Path First)',
  'VLAN (Virtual Local Area Network)',
  'VPN klient',
  'VPN serwer',
  'proxy',
  'DMZ (Demilitarized Zone)',
  'IDS (Intrusion Detection System)',
  'IPS (Intrusion Prevention System)',
  'sieć mesh',
  'sieć ad hoc',
  'zdalny dostęp',
  'protokół RDP (Remote Desktop Protocol)',
  'SSH (Secure Shell)',
  'zdalne zarządzanie siecią'
];

List<String> hardwareList = [
  'Procesor',
  'pamięć RAM',
  'dysk twardy',
  'dysk SSD',
  'karta graficzna',
  'płyta główna',
  'zasilacz',
  'obudowa komputerowa',
  'monitor',
  'klawiatura',
  'mysz',
  'drukarka',
  'skaner',
  'karta sieciowa',
  'karta dźwiękowa',
  'głośniki',
  'mikrofon',
  'słuchawki',
  'kamera internetowa',
  'napęd CD/DVD',
  'chłodzenie procesora',
  'chłodzenie wodne',
  'wentylator',
  'hub USB',
  'dysk zewnętrzny',
  'pendrive',
  'karta pamięci',
  'adapter Bluetooth',
  'modem',
  'router',
  'switch sieciowy',
  'kabel Ethernet',
  'kabel HDMI',
  'kabel USB',
  'adapter sieciowy',
  'stacja dokująca',
  'podkładka pod mysz',
  'podstawka chłodząca',
  'filtr prywatyzujący',
  'czytnik kart pamięci',
  'kontroler gier',
  'joystick',
  'kierownica do gier',
  'gamepad',
  'VR headset',
  'zestaw do czyszczenia komputera',
  'zasilacz awaryjny (UPS)',
  'zestaw śrubokrętów do komputera',
  'pasta termoprzewodząca',
  'taśma termoprzewodząca'
];

List<String> sportsList = [
  'Piłka nożna',
  'koszykówka',
  'baseball',
  'futbol amerykański',
  'hokej na lodzie',
  'rugby',
  'golf',
  'boks',
  'zapasy',
  'kolarstwo',
  'narciarstwo',
  'snowboarding',
  'surfing',
  'tenis',
  'tenis stołowy',
  'squash',
  'badminton',
  'wspinaczka',
  'żeglarstwo',
  'pływanie',
  'pływanie synchroniczne',
  'skoki do wody',
  'żużel',
  'jazda na motocyklu',
  'MotoGP',
  'Formuła 1',
  'wioślarstwo',
  'siatkówka',
  'piłka ręczna',
  'cricket',
  'snooker',
  'kitesurfing',
  'jazda konna',
  'bieganie',
  'maraton',
  'triathlon',
  'karate',
  'taekwondo',
  'judo',
  'szermierka',
  'biegi narciarskie',
  'skoki narciarskie',
  'hokej na trawie',
  'kajakarstwo',
  'łucznictwo',
  'szachy',
  'gimnastyka',
  'snowcross',
  'narciarstwo freestylowe',
  'narciarstwo alpejskie',
  'narciarstwo dowolne'
];

List<String> footballList = [
  'Bramkarz',
  'obrońca',
  'środkowy obrońca',
  'boczny obrońca',
  'napastnik',
  'środkowy napastnik',
  'skrzydłowy',
  'kapitan drużyny',
  'strzał',
  'gol',
  'asysta',
  'rzut rożny',
  'rzut karny',
  'spalony',
  'wymiana zawodników',
  'trener',
  'sędzia',
  'kibice',
  'trybuny',
  'boisko',
  'piłka',
  'narożnik boiska',
  'połowa boiska',
  'przerwa',
  'dogrywka',
  'rzuty karne',
  'liga',
  'mistrzostwa',
  'turniej',
  'kwalifikacje',
  'drużyna',
  'przeciwnik',
  'faul',
  'kartka żółta',
  'kartka czerwona',
  'stadion',
  'bramka',
  'wyrzut z autu',
  'rzut wolny',
  'zdobycie bramki',
  'rywalizacja',
  'wynik meczu',
  'remis',
  'zwycięstwo',
  'porażka',
  'koszulka drużyny',
  'buty piłkarskie',
  'rękawice bramkarskie',
  'koszulka bramkarza',
  'spodenki',
  'getry',
  'trening piłkarski',
  'przyjęcie piłki'
];

List<String> footballersList = [
  "Cristiano Ronaldo",
  "Lionel Messi",
  "Neymar Jr.",
  "Kylian Mbappé",
  "Robert Lewandowski",
  "Mohamed Salah",
  "Sergio Ramos",
  "Kevin De Bruyne",
  "Karim Benzema",
  "Harry Kane",
  "Antoine Griezmann",
  "Luka Modrić",
  "Manuel Neuer",
  "Raheem Sterling",
  "Eden Hazard",
  "Paul Pogba",
  "Erling Haaland",
  "Bruno Fernandes",
  "Joshua Kimmich",
  "Thiago Alcântara",
  "Bruno Fernandes",
  "Thiago Alcântara",
  "Virgil van Dijk",
  "Alisson Becker",
  "Trent Alexander-Arnold",
  "Frenkie de Jong",
  "Marco Reus",
  "Jadon Sancho",
  "Thomas Müller",
  "Toni Kroos",
  "Gianluigi Donnarumma",
  "Romelu Lukaku",
  "Hakim Ziyech",
  "N'Golo Kanté",
  "Kalidou Koulibaly",
  "Casemiro",
  "Marcelo",
  "Sergio Agüero",
  "Romelu Lukaku",
  "Hakim Ziyech",
  "N'Golo Kanté",
  "Kalidou Koulibaly",
  "Casemiro",
  "Marcelo",
  "Sergio Agüero",
  "Zlatan Ibrahimović",
  "Paulo Dybala",
  "João Cancelo",
  "Kasper Schmeichel",
  "Bernardo Silva",
  "Andrés Iniesta",
  "Gerard Piqué",
  "Sergio Busquets"
];

List<String> polishFootballersList = [
  "Robert Lewandowski",
  "Krzysztof Piątek",
  "Arkadiusz Milik",
  "Wojciech Szczęsny",
  "Łukasz Piszczek",
  "Kamil Glik",
  "Piotr Zieliński",
  "Grzegorz Krychowiak",
  "Kamil Grosicki",
  "Jakub Blaszczykowski",
  "Łukasz Fabiański",
  "Bartosz Bereszyński",
  "Jan Bednarek",
  "Rafał Kurzawa",
  "Szymon Żurkowski",
  "Tomasz Kędziora",
  "Arkadiusz Reca",
  "Piotr Woźniacki",
  "Damian Kądzior",
  "Artur Jędrzejczyk",
  "Kamil Wilczek",
  "Krzysztof Piątek",
  "Maciej Rybus",
  "Przemysław Frankowski",
  "Bartłomiej Drągowski",
  "Karol Linetty",
  "Tomasz Frankowski",
  "Maciej Makuszewski",
  "Jakub Świerczok",
  "Arkadiusz Wozniak",
  "Arkadiusz Malarz",
  "Robert Gumny",
  "Sławomir Peszko",
  "Marcin Kamiński",
  "Karol Świderski",
  "Jarosław Niezgoda",
  "Michał Pazdan",
  "Szymon Marciniak",
  "Dawid Kownacki",
  "Tomasz Górski",
  "Artur Boruc",
  "Łukasz Teodorczyk",
  "Marcin Wasilewski",
  "Kamil Vacek",
  "Paweł Wszołek",
  "Tomasz Glik",
  "Marcin Kikut",
  "Mateusz Klich",
  "Sławomir Peszko",
  "Kamil Grosicki"
];
