List<String> hairsWordsList = [
  'farbowanie włosów',
  'strzyżenie',
  'modelowanie',
  'prostowanie włosów',
  'lokówka',
  'suszarka do włosów',
  'maska do włosów',
  'odżywka',
  'szampon',
  'tonowanie',
  'balejaż',
  'ombre',
  'sombre',
  'pasemka',
  'trwała ondulacja',
  'keratynowe prostowanie',
  'upięcia',
  'fryzury ślubne',
  'cieniowanie',
  'grzywka',
  'bob',
  'pixie cut',
  'undercut',
  'fade',
  'pompadour',
  'quiff',
  'warkocz francuski',
  'warkocz holenderski',
  'warkocz rybi ogon',
  'warkocz wodospad',
  'kok',
  'chignon',
  'twist',
  'cornrows',
  'afro',
  'dreadlocks',
  'hair tattoo',
  'włosy tęczowe',
  'włosy pastelowe',
  'brokat w włosach',
  'męskie strzyżenie',
  'bokserki',
  'fryzury męskie klasyczne',
  'fryzury na imprezę',
  'fryzury casual',
  'fryzury glamour',
  'henna do włosów',
  'laminowanie włosów',
  'peeling skóry głowy',
  'detoksykacja włosów',
  'olejowanie włosów',
  'fryzury z grzywką',
  'krótkie fryzury',
  'długie włosy',
  'włosy średniej długości',
  'fryzury z długich włosów',
  'fryzury z krótkich włosów',
  'fryzury z falami',
  'fryzury z lokami',
  'prostownica',
  'spray do włosów',
  'pianka do włosów',
  'żel do włosów',
  'wosk do włosów',
  'gumka do włosów',
  'spineczki',
  'wsuwki',
  'opaska do włosów',
  'tiara',
  'farba do włosów',
  'rozjaśniacz do włosów',
  'toner do włosów',
  'szampon koloryzujący',
  'szampon bez sulfatów',
  'fryzury retro',
  'fryzury vintage',
  'fryzury boho',
  'fryzury etniczne',
  'keratyna',
  'botox do włosów',
  'zabiegi na skórę głowy',
  'masaż głowy',
  'zabiegi przeciwłupieżowe',
  'zabiegi przeciw wypadaniu włosów',
  'przedłużanie włosów',
  'zagęszczanie włosów',
  'mikroringi',
  'taśmy do włosów',
  'clip-in',
  'hair flip',
  'fryzury asymetryczne',
  'fryzury z grzywką na bok',
  'fryzury z wygolonymi bokami',
  'fryzury z wygolonym tyłem',
  'fryzury z kolorowymi pasemkami',
  'fryzury z efektem mokrych włosów',
  'fryzury plażowe',
  'fryzury sportowe',
  'fryzury eleganckie',
  'fryzury na co dzień',
  'stylizacje na wydarzenia specjalne',
  'fryzury na bal',
  'fryzury na studniówkę',
  'fryzury na randkę',
  'fryzury na rozmowę kwalifikacyjną',
  'fryzury na wesele',
  'fryzury na festiwal'
];

List<String> nailsWordsList = [
  'lakierowanie paznokci',
  'hybryda',
  'manicure klasyczny',
  'manicure japoński',
  'pedicure',
  'zdobienia paznokci',
  'naklejki na paznokcie',
  'manicure francuski',
  'tipsy',
  'żel na paznokcie',
  'akryl na paznokcie',
  'manicure tytanowy',
  'lakier hybrydowy',
  'baza pod lakier',
  'top coat',
  'utwardzacz do paznokci',
  'odżywka do paznokci',
  'oliwka do skórek',
  'usuwanie skórek',
  'pilnikowanie paznokci',
  'polerowanie paznokci',
  'paznokcie sztuczne',
  'kształtowanie paznokci',
  'wzory na paznokcie',
  'paznokcie ombre',
  'baby boomer',
  'manicure wodny',
  'nail art',
  'brokat na paznokcie',
  'kropki na paznokcie',
  'linie na paznokcie',
  'paznokcie w kształcie migdała',
  'paznokcie kwadratowe',
  'paznokcie owalne',
  'paznokcie szpiczaste',
  'paznokcie ballerina',
  'naklejki wodne',
  'stemple do paznokci',
  'folia transferowa',
  'paznokcie marmurkowe',
  'paznokcie holograficzne',
  'chrom na paznokcie',
  'paznokcie neonowe',
  'paznokcie pastelowe',
  'paznokcie matowe',
  'zdobienia 3D',
  'kryształki na paznokcie',
  'perełki na paznokcie',
  'naklejki 3D',
  'malowanie aerografem',
  'lakier termiczny',
  'lakier magnetyczny',
  'lakier fluorescencyjny',
  'cieniowanie kolorów',
  'paznokcie minimalistyczne',
  'paznokcie geometryczne',
  'paznokcie z efektem lustra',
  'paznokcie z efektem kociego oka',
  'paznokcie z efektem syrenki',
  'długie paznokcie',
  'krótkie paznokcie',
  'paznokcie średniej długości',
  'zabiegi na paznokcie',
  'pielęgnacja paznokci',
  'odżywki wzmacniające',
  'olejek do paznokci',
  'lakier bazowy',
  'odżywka z keratyną',
  'odżywka z witaminami',
  'usuwanie lakieru hybrydowego',
  'usuwanie żelu',
  'usuwanie akrylu',
  'rekonstrukcja paznokcia',
  'wzmocnienie naturalnych paznokci',
  'nakładanie akrylu',
  'nakładanie żelu',
  'frenz nails',
  'wzory kwiatowe',
  'wzory zwierzęce',
  'paznokcie z cyrkoniami',
  'manicure ślubny',
  'manicure wieczorowy',
  'manicure na imprezę',
  'manicure na co dzień',
  'manicure na specjalne okazje',
  'paznokcie sezonowe',
  'paznokcie wakacyjne',
  'paznokcie na Boże Narodzenie',
  'paznokcie na Halloween',
  'paznokcie na Wielkanoc',
  'paznokcie na Walentynki',
  'stylizacje paznokci',
  'zdobienia ręczne paznokci',
  'zdobienia pędzelkiem',
  'zdobienia paznokci na sucho',
  'nakładanie folii na paznokcie',
  'paznokcie z efektem jeans',
  'paznokcie z efektem piasku'
];

List<String> raisingKidsWordsList = [
  'Karmienie piersią',
  'karmienie butelką',
  'zmiana pieluch',
  'kąpiel niemowlęcia',
  'czytanie bajek',
  'nauka mówienia',
  'nauka chodzenia',
  'robienie kanapek do szkoły',
  'pomoc w odrabianiu lekcji',
  'wizyty u pediatry',
  'szczepienia',
  'zabawy edukacyjne',
  'nauka jazdy na rowerze',
  'organizowanie przyjęć urodzinowych',
  'uczestnictwo w zebraniach szkolnych',
  'wybór przedszkola',
  'wybór szkoły',
  'nauka pływania',
  'nauka języków obcych',
  'rozwiązywanie konfliktów',
  'wycieczki rodzinne',
  'opieka nad dzieckiem',
  'opowiadanie historyjek na dobranoc',
  'nauka samodzielności',
  'nauka higieny',
  'organizacja czasu wolnego',
  'wychowanie emocjonalne',
  'rozpoznawanie talentów',
  'wsparcie w sporcie',
  'zajęcia muzyczne',
  'nauka rysowania',
  'nauka pisania',
  'zabawy na świeżym powietrzu',
  'nauka bezpieczeństwa',
  'nauka odpowiedzialności',
  'rozmowy o uczuciach',
  'kreatywne zabawy',
  'zabawy zręcznościowe',
  'zabawy rozwijające wyobraźnię',
  'zabawy sensoryczne',
  'nauka dobrych manier',
  'nauka szacunku',
  'rozwijanie umiejętności społecznych',
  'nauka zarządzania pieniędzmi',
  'nauka oszczędzania',
  'uczenie tolerancji',
  'rozwijanie empatii',
  'nauka radzenia sobie z emocjami',
  'organizowanie pikników',
  'zabawy w domu',
  'zabawy na placu zabaw',
  'uczestnictwo w zawodach sportowych',
  'udział w przedstawieniach szkolnych',
  'nauka gry na instrumencie',
  'nauka śpiewu',
  'uczestnictwo w warsztatach',
  'nauka gotowania',
  'nauka sprzątania',
  'organizowanie zabaw grupowych',
  'nauka jazdy na rolkach',
  'nauka jazdy na łyżwach',
  'opieka nad zwierzętami',
  'rozmowy o naturze',
  'nauka ekologii',
  'rozmowy o zdrowiu',
  'wsparcie w trudnych chwilach',
  'nauka zaradności',
  'nauka krytycznego myślenia',
  'rozwijanie kreatywności',
  'nauka bezpiecznego korzystania z internetu',
  'kontrola czasu spędzanego przed ekranem',
  'nauka poszanowania prywatności',
  'rozmowy o przyjaźni',
  'organizowanie wakacji',
  'nauka dbania o przyrodę',
  'wspólne gotowanie',
  'uczestnictwo w zajęciach pozaszkolnych',
  'nauka jazdy na hulajnodze',
  'nauka jazdy na nartach',
  'nauka gry w piłkę',
  'nauka gry w szachy',
  'organizowanie warsztatów rodzinnych',
  'udział w konkursach',
  'nauka gry w planszówki',
  'nauka gry w karty',
  'wspólne świętowanie tradycji rodzinnych',
  'rozmowy o bezpieczeństwie',
  'organizowanie wycieczek szkolnych',
  'nauka radzenia sobie z porażką',
  'nauka dzielenia się',
  'nauka współpracy',
  'wspieranie w rozwijaniu pasji',
  'nauka o zwierzętach',
  'nauka o roślinach',
  'rozmowy o zdrowym odżywianiu',
  'nauka dbania o własne ciało',
  'nauka szanowania innych',
  'nauka szanowania różnic',
  'wsparcie w rozwijaniu niezależności'
];

List<String> hairsItemsList = [
  'Suszarka do włosów',
  'prostownica',
  'lokówka',
  'szczotka do włosów',
  'grzebień',
  'nożyczki fryzjerskie',
  'maszynka do strzyżenia',
  'farba do włosów',
  'rozjaśniacz',
  'toner do włosów',
  'szampon',
  'odżywka',
  'maska do włosów',
  'serum do włosów',
  'olejek do włosów',
  'pianka do włosów',
  'żel do włosów',
  'lakier do włosów',
  'gumka do włosów',
  'spinki do włosów',
  'wsuwki',
  'opaska do włosów',
  'chustka do włosów',
  'diadem',
  'tiara',
  'wałki do włosów',
  'papiloty',
  'folia fryzjerska',
  'czepek do farbowania',
  'miseczka do farby',
  'pędzel do farby',
  'rękawiczki jednorazowe',
  'fartuch fryzjerski',
  'peleryna fryzjerska',
  'woda utleniona',
  'saszetki z kolorem',
  'toniki do włosów',
  'spray nabłyszczający',
  'spray chroniący przed ciepłem',
  'spray teksturujący',
  'sól morska w sprayu',
  'pudry do włosów',
  'włosy clip-in',
  'przedłużanie włosów na taśmie',
  'przedłużanie włosów na keratynie',
  'przedłużanie włosów mikroringami',
  'peruki',
  'turbany',
  'nakrycia głowy',
  'chustki jedwabne',
  'bandany',
  'brokat do włosów',
  'gumki Invisibobble',
  'wałek do koka',
  'koczki',
  'włosy syntetyczne',
  'kredy do włosów',
  'farby w sprayu',
  'farby w kredce',
  'szamponetki',
  'toniki bez amoniaku',
  'szampony koloryzujące',
  'szampony przeciwłupieżowe',
  'szampony do włosów suchych',
  'szampony do włosów farbowanych',
  'szampony do włosów cienkich',
  'szampony do włosów kręconych',
  'odżywki bez spłukiwania',
  'odżywki w sprayu',
  'odżywki do włosów suchych',
  'odżywki do włosów farbowanych',
  'odżywki do włosów cienkich',
  'odżywki do włosów kręconych',
  'maski do włosów suchych',
  'maski do włosów farbowanych',
  'maski do włosów cienkich',
  'maski do włosów kręconych',
  'olejki do włosów suchych',
  'olejki do włosów farbowanych',
  'olejki do włosów cienkich',
  'olejki do włosów kręconych',
  'serum do końcówek',
  'serum wygładzające',
  'serum nabłyszczające',
  'serum przeciw puszeniu się włosów',
  'serum ochronne przed ciepłem',
  'serum do włosów suchych',
  'serum do włosów farbowanych',
  'serum do włosów cienkich',
  'serum do włosów kręconych',
  'kosmetyki do stylizacji',
  'kosmetyki do pielęgnacji',
  'kosmetyki do regeneracji',
  'kosmetyki do odbudowy włosów',
  'spraye do włosów',
  'pianki do włosów',
  'żele do włosów',
  'lakiery do włosów',
  'pasty do włosów',
  'woski do włosów',
  'kremy do włosów',
  'balsamy do włosów'
];

List<String> wardrobeItemsList = [
  'Sukienka',
  'spódnica',
  'bluzka',
  'koszula',
  'sweter',
  'marynarka',
  'płaszcz',
  'kurtka',
  'spodnie',
  'jeansy',
  'legginsy',
  'szorty',
  'bluza',
  't-shirt',
  'top',
  'kamizelka',
  'tunika',
  'cardigan',
  'kombinezon',
  'body',
  'bielizna',
  'biustonosz',
  'majtki',
  'pończochy',
  'rajstopy',
  'szalik',
  'czapka',
  'rękawiczki',
  'pasek',
  'torebka',
  'buty',
  'szpilki',
  'botki',
  'kozaki',
  'sandały',
  'baleriny',
  'trampki',
  'kapcie',
  'zegarek',
  'naszyjnik',
  'kolczyki',
  'bransoletka',
  'pierścionek',
  'broszka',
  'okulary przeciwsłoneczne',
  'okulary korekcyjne',
  'chustka',
  'apaszka',
  'parasol',
  'płaszcz przeciwdeszczowy',
  'biżuteria',
  'portfel',
  'szal',
  'kimono',
  'dres',
  'piżama',
  'szlafrok',
  'stroj kąpielowy',
  'bikini',
  'tankini',
  'pareo',
  'czapka z daszkiem',
  'czapka zimowa',
  'beret',
  'kapelusz',
  'rękawiczki bez palców',
  'etola',
  'futro',
  'ponczo',
  'narzutka',
  'bolerko',
  'kurtka puchowa',
  'kurtka skórzana',
  'kurtka jeansowa',
  'kurtka wiatrówka',
  'kurtka bomberka',
  'kurtka parka',
  'płaszcz wełniany',
  'płaszcz trencz',
  'płaszcz skórzany',
  'płaszcz pikowany',
  'spódnica ołówkowa',
  'spódnica plisowana',
  'spódnica tiulowa',
  'spódnica maxi',
  'spódnica mini',
  'spódnica midi',
  'spódnica trapezowa',
  'spódnica asymetryczna',
  'sukienka wieczorowa',
  'sukienka koktajlowa',
  'sukienka letnia',
  'sukienka maxi',
  'sukienka midi',
  'sukienka mini',
  'sukienka ołówkowa',
  'sukienka trapezowa',
  'sukienka z falbanami',
  'sukienka z rozcięciem',
  'koszulka nocna',
  'koszulka na ramiączkach',
  'koszulka z długim rękawem',
  'bluzka z krótkim rękawem',
  'bluzka z długim rękawem',
  'bluzka bez rękawów',
  'bluzka z falbanami',
  'bluzka z kołnierzykiem'
];

List<String> kitchenItemsList = [
  'Patelnia',
  'garnek',
  'rondel',
  'deska do krojenia',
  'nóż kuchenny',
  'łyżka drewniana',
  'trzepaczka',
  'mikser ręczny',
  'blender',
  'robot kuchenny',
  'toster',
  'czajnik',
  'ekspres do kawy',
  'wyciskarka do cytrusów',
  'otwieracz do puszek',
  'otwieracz do butelek',
  'tarka',
  'sito',
  'durszlak',
  'wałek do ciasta',
  'foremki do ciastek',
  'miska',
  'salaterka',
  'chlebak',
  'pojemniki na przyprawy',
  'miarka kuchenna',
  'łopatka',
  'szczypce kuchenne',
  'termometr kuchenny',
  'młynek do pieprzu',
  'młynek do soli',
  'korkociąg',
  'szpatułka',
  'forma do pieczenia',
  'puszka na kawę/herbatę',
  'podstawka pod gorące',
  'fartuch kuchenny',
  'rękawice kuchenne',
  'ściereczki kuchenne',
  'ręcznik papierowy',
  'folia aluminiowa',
  'folia spożywcza',
  'papier do pieczenia',
  'pojemniki na żywność',
  'koszyk na owoce',
  'taca',
  'podkładki na stół',
  'waga kuchenna',
  'ścierka do naczyń',
  'zmywak',
  'szczotka do mycia naczyń',
  'dozownik do mydła',
  'kosz na śmieci',
  'filtry do wody',
  'butelka na wodę',
  'słoiki',
  'karafka',
  'kubki',
  'filiżanki',
  'szklanki',
  'kieliszki',
  'dzbanek',
  'cukiernica',
  'mlecznik',
  'talerze',
  'misek do sałatek',
  'talerzyki deserowe',
  'półmiski',
  'sztućce (łyżki',
  'widelce',
  'noże)',
  'nożyce kuchenne',
  'obieraczka do warzyw',
  'maszynka do mielenia mięsa',
  'deska do serwowania',
  'wyciskarka do czosnku',
  'maszynka do makaronu',
  'stojak na noże',
  'stojak na ręczniki papierowe',
  'pojemnik na olej/ocet',
  'przyprawniki',
  'koszyk na chleb',
  'torba na zakupy',
  'butelka termiczna',
  'lunchbox',
  'foremki do lodu',
  'kawiarka',
  'parowar',
  'garnki do gotowania na parze',
  'suszarka do naczyń',
  'miska do miksera',
  'kubek miarowy',
  'miseczki do dipów',
  'talerzyki do sushi',
  'pałeczki do sushi',
  'pędzel kuchenny',
  'praska do ziemniaków',
  'praska do owoców',
  'łopatka do ciasta',
  'pokrywki do garnków',
  'sitko do herbaty',
  'stojak na wino',
  'suszarka do warzyw i owoców',
  'podkładki antypoślizgowe',
  'rękaw do pieczenia',
  'formy do babeczek',
  'formy do tarty',
  'mata do pieczenia',
  'pojemnik na jajka'
];

List<String> generalListWomen = [
  'torebka damska',
  'szpilki',
  'sukienka',
  'kosmetyczka',
  'lakier do paznokci',
  'biżuteria',
  'broszka',
  'szalik',
  'perfumy',
  'róż do policzków',
  'tusz do rzęs',
  'cień do powiek',
  'pomadka',
  'balsam do ust',
  'krem do twarzy',
  'serum do twarzy',
  'maseczka do twarzy',
  'odżywka do włosów',
  'szampon do włosów',
  'prostownica do włosów',
  'lokówka',
  'spinki do włosów',
  'gumki do włosów',
  'opaska do włosów',
  'chustka',
  'pierścionek',
  'kolczyki',
  'naszyjnik',
  'bransoletka',
  'zegarek damski',
  'okulary przeciwsłoneczne',
  'okulary korekcyjne',
  'spódnica',
  'bluzka',
  'sweter',
  'kardigan',
  'kurtka',
  'płaszcz',
  'legginsy',
  'jeansy',
  'bluza',
  'body',
  'biustonosz',
  'majtki',
  'pończochy',
  'rajstopy',
  'piżama',
  'szlafrok',
  'strój kąpielowy',
  'bikini',
  'buty sportowe',
  'baleriny',
  'botki',
  'kozaki',
  'trampki',
  'sandały',
  'kapcie',
  'fartuch kuchenny',
  'rękawice kuchenne',
  'notes',
  'długopis',
  'książka',
  'tablet',
  'smartfon',
  'zeszyt',
  'organizer',
  'plecak',
  'torba na laptopa',
  'etui na telefon',
  'powerbank',
  'lusterko kieszonkowe',
  'szczotka do włosów',
  'grzebień',
  'pęseta',
  'nożyczki do paznokci',
  'pilnik do paznokci',
  'krem do rąk',
  'mydło',
  'żel pod prysznic',
  'sól do kąpieli',
  'olejek do kąpieli',
  'świeca zapachowa',
  'poduszka',
  'kołdra',
  'pościel',
  'ręcznik',
  'ręcznik do twarzy',
  'wałek do ciasta',
  'foremki do ciastek',
  'blender',
  'mikser',
  'czajnik',
  'ekspres do kawy',
  'filiżanka',
  'kubek',
  'talerz',
  'miseczka',
  'szklanka',
  'karafka',
  'waza',
  'słoik',
  'pojemnik na żywność',
  'patelnia',
  'garnek',
  'rondel',
  'deska do krojenia',
  'nóż kuchenny',
  'taca',
  'podkładki na stół',
  'wazon',
  'ramka na zdjęcia',
  'zasłony',
  'dywanik'
];

List<String> colorsList = [
  'Błękitny Tiffany',
  'róż pudrowy',
  'burgund',
  'szmaragdowa zieleń',
  'lawendowy',
  'brzoskwiniowy',
  'koralowy',
  'morski',
  'fuksja',
  'indygo',
  'kremowy',
  'magenta',
  'taupe',
  'szafirowy',
  'miętowy',
  'złoty róż',
  'cytrynowy',
  'pastelowy róż',
  'beżowy',
  'ametystowy',
  'turkusowy',
  'khaki',
  'fioletowy heather',
  'jasny denim',
  'czerwień wina',
  'szary melanż',
  'perłowy',
  'odcień nude',
  'miętowa zieleń',
  'mokka',
  'aqua',
  'platynowy',
  'cynamonowy',
  'odcień szafranu',
  'oliwkowy',
  'szampan',
  'granatowy',
  'ciemna śliwka',
  'jasna oliwka',
  'róż quartz',
  'musztardowy',
  'odcień miedzi',
  'szary grafitowy',
  'odcień kości słoniowej',
  'wenge',
  'lawendowa mgła',
  'fuksjowy róż',
  'jasny bursztyn',
  'róż antyczny',
  'wodny niebieski'
];

List<String> psychologyList = [
  'Inteligencja emocjonalna',
  'motywacja',
  'percepcja',
  'osobowość',
  'stres',
  'terapia',
  'nieświadomość',
  'zaburzenia lękowe',
  'depresja',
  'kognitywizm',
  'behawioryzm',
  'psychoanaliza',
  'rozwój osobisty',
  'asertywność',
  'empatia',
  'samoświadomość',
  'mindfulness',
  'inteligencja',
  'pamięć',
  'uczenie się',
  'zachowanie',
  'komunikacja interpersonalna',
  'zdrowie psychiczne',
  'terapia poznawczo-behawioralna',
  'psychologia pozytywna',
  'psychoterapia',
  'adaptacja',
  'resiliencja',
  'samoocena',
  'samoakceptacja',
  'tożsamość',
  'mechanizmy obronne',
  'neurony lustrzane',
  'empatia',
  'umiejętności społeczne',
  'inteligencja społeczna',
  'inteligencja interpersonalna',
  'inteligencja intrapersonalna',
  'psychologia kliniczna',
  'psychologia rozwojowa',
  'psychologia społeczna',
  'psychologia zdrowia',
  'psychologia pracy',
  'psychologia sportu',
  'psychologia edukacyjna',
  'psychologia ewolucyjna',
  'psychologia poznawcza',
  'psychologia osobowości',
  'psychologia behawioralna',
  'psychologia emocji'
];

List<String> housePlantsList = [
  'Monstera',
  'fikus',
  'zamiokulkas',
  'sansewieria',
  'aloes',
  'skrzydłokwiat',
  'pelargonia',
  'maranta',
  'kalatea',
  'fiołek afrykański',
  'paproć',
  'palma areka',
  'palma kentia',
  'kaktus',
  'sukulenty',
  'dracena',
  'hoya',
  'ananas',
  'aglaonema',
  'begonia',
  'kalanchoe',
  'pilea',
  'filodendron',
  'gynura',
  'chlorophytum',
  'aechmea',
  'orchidea',
  'aspidistra',
  'kroton',
  'agawa',
  'anturium',
  'kaladium',
  'cykas',
  'dieffenbachia',
  'epipremnum',
  'fittonia',
  'haworthia',
  'hippeastrum',
  'juka',
  'syngonium',
  'tillandsia',
  'tradescantia',
  'urzeczka',
  'yucca',
  'zamioculcas zamiifolia',
  'scindapsus',
  'spatifilum',
  'strelicja',
  'szeflera',
  'szydłownica'
];

List<String> skinCareList = [
  'Krem nawilżający',
  'tonik',
  'serum do twarzy',
  'maseczka do twarzy',
  'peeling',
  'olejek do twarzy',
  'krem przeciwzmarszczkowy',
  'krem pod oczy',
  'krem z filtrem SPF',
  'woda micelarna',
  'mleczko do demakijażu',
  'żel do mycia twarzy',
  'pianka do mycia twarzy',
  'esencja do twarzy',
  'płyn do tonizacji',
  'balsam do ciała',
  'masło do ciała',
  'olejek do ciała',
  'scrub do ciała',
  'krem do rąk',
  'krem do stóp',
  'krem do ciała',
  'balsam po goleniu',
  'krem do golenia',
  'żel aloesowy',
  'kwas hialuronowy',
  'retinol',
  'witamina C',
  'witamina E',
  'kwas salicylowy',
  'kwas glikolowy',
  'kwas mlekowy',
  'kwas azelainowy',
  'benzoesan sodu',
  'niacynamid',
  'panthenol',
  'alantoina',
  'ekstrakt z aloesu',
  'ekstrakt z ogórka',
  'ekstrakt z zielonej herbaty',
  'ekstrakt z rumianku',
  'kwas ferulowy',
  'peptydy',
  'ceramidy',
  'kolagen',
  'elastyna',
  'kwas linolowy',
  'kwas oleinowy',
  'olej arganowy',
  'olej jojoba',
  'olej kokosowy'
];

List<String> actorsList = [
  'Brad Pitt',
  'Leonardo DiCaprio',
  'Tom Hanks',
  'Johnny Depp',
  'Robert Downey Jr.',
  'Denzel Washington',
  'Morgan Freeman',
  'George Clooney',
  'Samuel L. Jackson',
  'Matt Damon',
  'Will Smith',
  'Harrison Ford',
  'Keanu Reeves',
  'Tom Cruise',
  'Hugh Jackman',
  'Chris Hemsworth',
  'Dwayne Johnson',
  'Ryan Reynolds',
  'Mark Wahlberg',
  'Christian Bale',
  'Daniel Day-Lewis',
  'Russell Crowe',
  'Joaquin Phoenix',
  'Al Pacino',
  'Robert De Niro',
  'Clint Eastwood',
  'Sean Connery',
  'Liam Neeson',
  'Daniel Craig',
  'Colin Firth',
  'Anthony Hopkins',
  'Jeff Goldblum',
  'Kevin Costner',
  'Idris Elba',
  'Benedict Cumberbatch',
  'Eddie Redmayne',
  'Michael Fassbender',
  'Jake Gyllenhaal',
  'Chris Pratt',
  'Chris Evans',
  'Robert Pattinson',
  'Ben Affleck',
  'Jason Statham',
  'Vin Diesel',
  'Sylvester Stallone',
  'John Travolta',
  'Jim Carrey',
  'Adam Sandler',
  'Will Ferrell',
  'Ben Stiller',
  'Meryl Streep',
  'Charlize Theron',
  'Jennifer Lawrence',
  'Scarlett Johansson',
  'Angelina Jolie',
  'Natalie Portman',
  'Nicole Kidman',
  'Julia Roberts',
  'Cate Blanchett',
  'Kate Winslet',
  'Sandra Bullock',
  'Emma Stone',
  'Jennifer Aniston',
  'Reese Witherspoon',
  'Anne Hathaway',
  'Emma Watson',
  'Keira Knightley',
  'Natalie Wood',
  'Audrey Hepburn',
  'Grace Kelly',
  'Marilyn Monroe',
  'Elizabeth Taylor',
  'Meryl Streep',
  'Charlize Theron',
  'Jennifer Lawrence',
  'Scarlett Johansson',
  'Angelina Jolie',
  'Natalie Portman',
  'Nicole Kidman',
  'Julia Roberts',
  'Cate Blanchett',
  'Kate Winslet',
  'Sandra Bullock',
  'Emma Stone',
  'Jennifer Aniston',
  'Reese Witherspoon',
  'Anne Hathaway',
  'Emma Watson',
  'Keira Knightley',
  'Natalie Wood',
  'Audrey Hepburn',
  'Grace Kelly',
  'Marilyn Monroe',
  'Elizabeth Taylor'
];

List<String> polishActorsList = [
  'Jerzy Stuhr',
  'Krystyna Janda',
  'Andrzej Seweryn',
  'Maja Ostaszewska',
  'Bogusław Linda',
  'Magdalena Cielecka',
  'Janusz Gajos',
  'Agnieszka Holland',
  'Paweł Małaszyński',
  'Dorota Kolak',
  'Robert Więckiewicz',
  'Joanna Kulig',
  'Daniel Olbrychski',
  'Małgorzata Kożuchowska',
  'Cezary Pazura',
  'Anna Dymna',
  'Borys Szyc',
  'Agata Buzek',
  'Wojciech Pszoniak',
  'Katarzyna Figura',
  'Andrzej Chyra',
  'Krzysztof Kowalewski',
  'Beata Tyszkiewicz',
  'Krzysztof Globisz',
  'Agnieszka Grochowska',
  'Janusz Korczak',
  'Anna Mucha',
  'Michał Żebrowski',
  'Grażyna Szapołowska',
  'Janusz Gajos',
  'Danuta Szaflarska',
  'Marek Kondrat',
  'Krzysztof Stroiński',
  'Maria Pakulnis',
  'Zbigniew Zamachowski',
  'Joanna Szczepkowska',
  'Tomasz Karolak',
  'Katarzyna Zielonka',
  'Piotr Adamczyk',
  'Anna Dereszowska',
  'Cezary Żak',
  'Małgorzata Socha',
  'Michał Żebrowski',
  'Olga Bołądź',
  'Tomasz Kot',
  'Krzysztof Pieczyński',
  'Katarzyna Bujakiewicz',
  'Piotr Fronczewski',
  'Maria Ciunelis',
  'Maciej Stuhr',
  'Joanna Brodzik',
  'Robert Gonera',
  'Agnieszka Dygant',
  'Andrzej Grabowski'
];
